name: Build and Push Docker Image

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

env:
  REGISTRY_URL: ${{ secrets.REGISTRY_URL }}
  IMAGE_NAME: ${{ secrets.IMAGE_NAME }}
  DNS_SERVER: ${{ secrets.DNS_SERVER }}
  REPO_URL: ${{ secrets.REPO_URL }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Configure DNS
        run: |
          # Install required tools
          apt-get update && apt-get install -y iputils-ping dnsutils
          
          # Debug environment variables
          echo "Checking environment variables:"
          echo "DNS_SERVER: ${DNS_SERVER:-not set}"
          echo "REPO_URL: ${REPO_URL:-not set}"
          
          # Backup original resolv.conf
          cp /etc/resolv.conf /etc/resolv.conf.bak
          
          # Configure DNS with validation
          if [ -z "$DNS_SERVER" ]; then
            echo "Error: DNS_SERVER is not set"
            exit 1
          fi
          
          # Configure DNS
          cat > /etc/resolv.conf << EOF
          nameserver ${DNS_SERVER}
          options timeout:2 attempts:3 rotate
          EOF
          
          # Verify DNS configuration
          echo "Current DNS configuration:"
          cat /etc/resolv.conf
          
          echo "Testing DNS resolution:"
          host ${REPO_URL} || true
          dig +short ${REPO_URL} || true
          
          # Add hosts entry
          if [ -n "$DNS_SERVER" ] && [ -n "$REPO_URL" ]; then
            echo "${DNS_SERVER} ${REPO_URL}" >> /etc/hosts
            echo "Added hosts entry:"
            tail -n 1 /etc/hosts
          else
            echo "Warning: Could not add hosts entry - missing DNS_SERVER or REPO_URL"
          fi

      - name: Configure Git DNS
        run: |
          # Configure Git to use the correct DNS
          git config --global http.sslVerify false
          git config --global --add safe.directory /workspace/Development/jupzi
          
          # Test git connection
          echo "Testing git connection..."
          git ls-remote https://${REPO_URL} || true

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Registry
        if: secrets.REGISTRY_USERNAME != '' && secrets.REGISTRY_PASSWORD != ''
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY_URL }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=tag
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and Push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=${{ env.REGISTRY_URL }}/${{ env.IMAGE_NAME }}:buildcache
          cache-to: type=registry,ref=${{ env.REGISTRY_URL }}/${{ env.IMAGE_NAME }}:buildcache,mode=max
          build-args: |
            NODE_ENV=production
            VERSION=${{ github.ref_name }}
            BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/*.zip
            dist/*.tar.gz
          generate_release_notes: true
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 